modify pools to also carry ekg stats
hasura/pg-client-hs pull request #31
Opened 2021-03-17 15:54 UTC by evertedsphere

required for the corresponding feature in pro monitoring

2021-03-19 07:37 UTC, ecthiender commented on src/Database/PG/Query/Pool.hs
> +    _connAcquireTime :: Distribution
If I understand #798 correctly, we want the time taken to acquire connections from the connection pool. Is that right?

Although, I think its a great idea to capture the time to postgres as well. We should definitely have this. But, I think we have to add another `Distribution` to track the same thing but for connections from pool.

Possibly in this function: https://github.com/hasura/pg-client-hs/blob/swann/pool-metrics/src/Database/PG/Query/Pool.hs#L273 ?

2021-04-07 07:45 UTC, ecthiender approved these changes

2021-04-07 08:48 UTC, vladciobanu requested changes
I wish I had a concrete proposal of how to make this library extensible and have `EKG` be an extension in the monorepo. However, I'm not sure how to do that without providing callback functions like `beforeConnectionAcquisition`, `afterConnectionAcquisition` as `IO ()` functions, and I like that less than the current implementation.

However, I still think we should keep this as an implementation detail, so I would not export the constructor, see comment below.

2021-04-07 08:48 UTC, vladciobanu commented on src/Database/PG/Query/Pool.hs
> +  , PGPoolStats(..)
I would rather keep the `PGPool` hidden and provide a function `PGPool -> PGPoolStats`

2021-04-07 13:56 UTC, vladciobanu approved these changes
:+1:

2021-04-07 13:59 UTC, merged